---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-operator
  labels:
    control-plane: logging-operator
spec:
  selector:
    matchLabels:
      control-plane: logging-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: logging-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: quay.io/opstree/logging-operator:v0.2.0
        imagePullPolicy: Always
        name: logging-operator
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
      serviceAccount: logging-operator
      serviceAccountName: logging-operator
