NAME: my-skywalking
LAST DEPLOYED: Fri Mar 12 00:57:41 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
---
# Source: skywalking/templates/mysql-init.job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "my-skywalking-mysql-init"
  labels:
    app: skywalking
    chart: skywalking-8.1.0-alpha.1
    component: "my-skywalking-job"
    heritage: Helm
    release: my-skywalking
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: "my-skywalking-mysql-init"
      labels:
        app: skywalking
        component: "my-skywalking-job"
        release: my-skywalking
    spec:
      restartPolicy: Never
      initContainers:
      - name: mysqlcheck
        imagePullPolicy: IfNotPresent
        image: "registry.cn-shanghai.aliyuncs.com/c7n/mysql-client:10.2.15-r0"
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASS
          value: "password"
        args:
        - -c
        - $(while ! mysqlcheck --host="${MYSQL_HOST}" --port="${MYSQL_PORT}" --user="${MYSQL_USER}" --password="${MYSQL_PASS}" information_schema; do sleep 3; done)
        command:
        - /bin/sh
      containers:
      - name: skywalking-oap
        image: "registry.cn-shanghai.aliyuncs.com/c7n/skywalking-oap-server:8.1.0-es7"
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms2g -Dmode=init"
        - name: SW_STORAGE
          value: "mysql"
        - name: SW_JDBC_URL
          value: "jdbc:mysql://mysql:3306/skywalking?serverTimezone=Asia/Shanghai"
        - name: SW_DATA_SOURCE_USER
          value: "root"
        - name: SW_DATA_SOURCE_PASSWORD
          value: "password"
        - name: TZ
          value: "Asia/Shanghai"
MANIFEST:
---
# Source: skywalking/templates/oap-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: skywalking
    chart: skywalking-8.1.0-alpha.1
    component: "skywalking-oap"
    heritage: Helm
    release: my-skywalking
  name: my-skywalking-skywalking-oap
---
# Source: skywalking/templates/oap-role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-skywalking
  labels:
    app: skywalking
    chart: "skywalking-8.1.0-alpha.1"
    release: "my-skywalking"
    heritage: "Helm"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
# Source: skywalking/templates/oap-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-skywalking
  labels:
    app: skywalking
    chart: "skywalking-8.1.0-alpha.1"
    release: "my-skywalking"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-skywalking
subjects:
  - kind: ServiceAccount
    name: my-skywalking-skywalking-oap
    namespace: default
---
# Source: skywalking/templates/oap-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-skywalking-skywalking-oap
  labels:
    app: skywalking
    chart: skywalking-8.1.0-alpha.1
    component: "skywalking-oap"
    heritage: Helm
    release: my-skywalking
spec:
  type: ClusterIP
  ports:
  - port: 12800
    name: rest
  - port: 11800
    name: grpc
  selector:
    app: skywalking
    component: "skywalking-oap"
    release: my-skywalking
---
# Source: skywalking/templates/ui-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
    chart: skywalking-8.1.0-alpha.1
    component: "skywalking-ui"
    heritage: Helm
    release: my-skywalking
  name: my-skywalking-skywalking-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

  selector:
    app: skywalking
    component: "skywalking-ui"
    release: my-skywalking
---
# Source: skywalking/templates/oap-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skywalking
    chart: skywalking-8.1.0-alpha.1
    component: "skywalking-oap"
    heritage: Helm
    release: my-skywalking
  name: my-skywalking-skywalking-oap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skywalking
      component: "skywalking-oap"
      release: my-skywalking
  template:
    metadata:
      labels:
        app: skywalking
        component: "skywalking-oap"
        release: my-skywalking
    spec:
      serviceAccountName: my-skywalking-skywalking-oap
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "skywalking"
                  release: "my-skywalking"
                  component: "skywalking-oap"
      initContainers:
      - name: mysqlcheck
        imagePullPolicy: IfNotPresent
        image: "registry.cn-shanghai.aliyuncs.com/c7n/mysql-client:10.2.15-r0"
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASS
          value: "password"
        args:
        - -c
        - $(while ! mysqlcheck --host="${MYSQL_HOST}" --port="${MYSQL_PORT}" --user="${MYSQL_USER}" --password="${MYSQL_PASS}" information_schema; do sleep 3; done)
        command:
        - /bin/sh
      containers:
      - name: skywalking-oap
        image: "registry.cn-shanghai.aliyuncs.com/c7n/skywalking-oap-server:8.1.0-es7"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        env:
        - name: JAVA_OPTS
          value: "-Xmx2g -Xms2g -Dmode=no-init"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "default"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=skywalking,release=my-skywalking,component=skywalking-oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: "mysql"
        - name: SW_JDBC_URL
          value: "jdbc:mysql://mysql:3306/skywalking?serverTimezone=Asia/Shanghai"
        - name: SW_DATA_SOURCE_USER
          value: "root"
        - name: SW_DATA_SOURCE_PASSWORD
          value: "password"
        - name: TZ
          value: "Asia/Shanghai"
---
# Source: skywalking/templates/ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-skywalking-skywalking-ui
  labels:
    app: skywalking
    chart: skywalking-8.1.0-alpha.1
    component: "skywalking-ui"
    heritage: Helm
    release: my-skywalking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking
      component: "skywalking-ui"
      release: my-skywalking
  template:
    metadata:
      labels:
        app: skywalking
        component: "skywalking-ui"
        release: my-skywalking
    spec:
      containers:
      - name: skywalking-ui
        image: registry.cn-shanghai.aliyuncs.com/c7n/skywalking-ui:8.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: page
        env:
        - name: SW_OAP_ADDRESS
          value: my-skywalking-skywalking-oap:12800
        - name: TZ
          value: "Asia/Shanghai"


Get the UI URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=skywalking,release=my-skywalking,component=skywalking-ui" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:8080 --namespace default
