---
apiVersion: logging.opstreelabs.in/v1alpha1
kind: Fluentd
metadata:
  name: fluentd-oos
  labels:
    organization: opstree
    owned-by: Abhishek
  namespace: logging-operator
spec:
  image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
  imagePullPolicy: "IfNotPresent"
  elasticsearch:
    host: "elasticsearch-cluster-ingestion"
    username: elastic
    password: "Opstree@1234"
    tlsEnabled: true
  logPrefix: namespace # namespace or podName
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi
  customConfiguration:
    kubelet.conf: |-
      <source>
        @type systemd
        @id in_systemd_kubelet
        matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]
        <storage>
          @type local
          persistent true
          path /var/log/fluentd-journald-kubelet-cursor.json
        </storage>
        <entry>
          fields_strip_underscores true
        </entry>
        read_from_head true
        tag kubelet
      </source>
