
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - elasticsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - elasticsearches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - fluentds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - fluentds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - indexlifecycles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - indexlifecycles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - indextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - indextemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - kibanas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.opstreelabs.in
  resources:
  - kibanas/status
  verbs:
  - get
  - patch
  - update
